/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wtoe_rtp_test2_RtpHandle */

#ifndef _Included_com_wtoe_jrtplib_RtpHandle
#define _Included_com_wtoe_jrtplib_RtpHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wtoe_rtp_test2_RtpHandle
 * Method:    initSendHandle
 * Signature: (ILjava/lang/String;ILcom/wtoe/rtp_test2/RtpListener;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wtoe_jrtplib_RtpHandle_initSendHandle
  (JNIEnv *, jclass, jint, jstring, jint, jobject);

/*
 * Class:     com_wtoe_rtp_test2_RtpHandle
 * Method:    initReceiveHandle
 * Signature: (Ljava/lang/String;ILcom/wtoe/rtp_test2/RtpListener;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wtoe_jrtplib_RtpHandle_initReceiveHandle
  (JNIEnv *, jclass, jstring, jint, jobject);

/*
 * Class:     com_wtoe_rtp_test2_RtpHandle
 * Method:    initReceiveHandle
 * Signature: (Ljava/lang/String;ILcom/wtoe/rtp_test2/RtpListener;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_wtoe_jrtplib_RtpHandle_initReceiveAndSendHandle
(JNIEnv *, jclass ,jstring , jint ,jstring , jint ,jobject );

/*
 * Class:     com_wtoe_rtp_test2_RtpHandle
 * Method:    sendByte
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wtoe_jrtplib_RtpHandle_sendH264Byte
  (JNIEnv *, jclass, jbyteArray, jint,jboolean);

/*
 * Class:     com_wtoe_rtp_test2_RtpHandle
 * Method:    sendByte
 * Signature: ([BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_wtoe_jrtplib_RtpHandle_sendRtpByte
        (JNIEnv *, jclass, jbyteArray, jint,jboolean);

/*
 * Class:     com_wtoe_rtp_test2_RtpHandle
 * Method:    finiRtp
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_wtoe_jrtplib_RtpHandle_finiRtp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
